module MonsterTraits

    type MonsterTrait = 
        | Aeon of string
        | Amphibious of string
        | Anadi of string
        | Angel of string
        | Aquatic of string
        | Archon of string
        | Azata of string
        | Boggard of string
        | Brutal of string
        | Caligni of string
        | Catfolk of string
        | Changeling of string
        | Daemon of string
        | Demon of string
        | Dero of string
        | Devil of string
        | Dhampir of string
        | Dinosaur of string
        | Drow of string
        | Duergar of string
        | Genie of string
        | Ghost of string
        | Ghoul of string
        | Gnoll of string
        | Golem of string
        | Gremlin of string
        | Hag of string
        | Inevitable of string
        | Kobold of string
        | Leshy of string
        | Lizardfolk of string
        | Merfolk of string
        | Mindless of string
        | Mummy of string
        | Mutant of string
        | Nymph of string
        | Olfactory of string
        | Orc of string
        | Protean of string
        | Psychopomp of string
        | Rakshasa of string
        | Ratfolk of string
        | Sea of string
        | Skeleton of string
        | Soulbound of string
        | Sprite of string
        | Swarm of string
        | Tengu of string
        | Troll of string
        | Vampire of string
        | Werecreature of string
        | Xulgath of string
        | Zombie of string