module UntypedTraits

    type UntypedTrait = 
        | Aasimar of string
        | Additive of string
        | Alchemical of string
        | Archetype of string
        | Attack of string
        | Auditory of string
        | Aura of string
        | Cantrip of string
        | Charm of string
        | Companion of string
        | Complex of string
        | Composition of string
        | Concentrate of string
        | Consecration of string
        | Contact of string
        | Curse of string
        | Darkness of string
        | Death of string
        | Dedication of string
        | Detection of string
        | Disease of string
        | Downtime of string
        | Duskwalker of string
        | Emotion of string
        | Environmental of string
        | Exploration of string
        | Extradimensional of string
        | Fear of string
        | Flourish of string
        | Focused of string
        | Fortune of string
        | General of string
        | Haunt of string
        | Healing of string
        | Incapacitation of string
        | Incorporeal of string
        | Infused of string
        | Instinct of string
        | Light of string
        | Linguistic of string
        | Litany of string
        | Magical of string
        | Manipulate of string
        | Mechanical of string
        | Mental of string
        | Metamagic of string
        | Minion of string
        | Misfortune of string
        | Morph of string
        | Move of string
        | Multiclass of string
        | Oath of string
        | Open of string
        | Polymorph of string
        | Possession of string
        | Precious of string
        | Prediction of string
        | Press of string
        | Rage of string
        | Reload of string
        | Revelation of string
        | Scrying of string
        | Secret of string
        | Shadow of string
        | Skill of string
        | Sleep of string
        | Splash of string
        | Stance of string
        | Summoned of string
        | Telepathy of string
        | Teleportation of string
        | Tiefling of string
        | Trap of string
        | Virulent of string
        | Visual of string
        | Wight of string
        | Wraith of string